apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helmi
spec:
  template:
    metadata:
      name: helmi
      labels:
        app: helmi
    spec:
      serviceAccountName: helmi
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: helmi
        image: monostream/helmi:latest
        imagePullPolicy: Always
        env:
        #- name: INGRESS_DOMAIN
        #  value: svc.example.com
        #- name: TILLER_NAMESPACE
        #  value: tiller
        #- name: HELM_NAMESPACE
        #  value: default
        #- name: CATALOG_URL
        #  value: https://example.com/catalog.zip
        #- name: REPOSITORY_URLS
        #  value: '{"stable":"https://kubernetes-charts.storage.googleapis.com"}'
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: helmi
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: helmi
              key: password
        ports:
        - name: helmi
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: helmi
spec:
  selector:
    app: helmi
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30000
